//This file is autogenerated by toolkit

namespace Hotel_listing.Application.Contracts.RepositoryManager.Command;
public interface ICommands : IDisposable
{
    ICountryCommand Country { get; }
    IHotelCommand Hotel { get; }
    Task Save();
}
