/// <summary>
///     This file is autogenerated by toolkit, next time you generate files again it wil be regenerated
///     If you want to do something custom with this class use partial instead
/// </summary>
using AutoMapper;
using Hotel_listing.Domain.Entitites;

namespace Hotel_listing.Application.Common;
public partial class MapperConfig : Profile
{
    public MapperConfig(bool isMapper)
    {
        CreateMap<Country, Country>().ReverseMap();
        CreateMap<Hotel, Hotel>().ReverseMap();
    }
}
