//This file is autogenerated by toolkit

namespace Hotel_listing.Application.Contracts.RepositoryManager.Query;
public interface IQuery : IDisposable
{
    ICountryQuery Country { get; }
    IHotelQuery Hotel { get; }
    Task Save();
}
