/// <summary>
///     This file is autogenerated by toolkit, next time you generate files again it wil be regenerated
///     If you want to do something custom with this class use partial instead
/// </summary>

using AutoMapper;
using Hotel_listing.Application.Contracts.RepositoryManager.DataAccessor;
using Hotel_listing.Application.Contracts.RepositoryManager.Query;
using Hotel_listing.Persistence.Contexts;

namespace Hotel_listing.Infrastructure.RepositoryManager.Query;
public partial class Query : IQuery
{
    private readonly DatabaseContext _context;
    private readonly IDataAccessor _db;
    private readonly IMapper _mapper;
    ICountryQuery _Country { get;set; }
    IHotelQuery _Hotel { get;set; }
    public Query(DatabaseContext context,IDataAccessor db,IMapper mapper)
    {
        _context = context;
        _db = db;
        _mapper = mapper;
    }
    public ICountryQuery Country => _Country ??= new CountryQuery(_context,_db,_mapper);
    public IHotelQuery Hotel => _Hotel ??= new HotelQuery(_context,_db, _mapper);
     
     public void Dispose() {
        _context.Dispose();
        GC.SuppressFinalize(this);
    }
    public async Task Save() {
        await _context.SaveChangesAsync();
    }
}
