//This file is autogenerated by toolkit
using Hotel_listing.Infrastructure.DatabaseManager.Context;
using Hotel_listing.Application.Contracts.RepositoryManager.Query;

namespace Hotel_listing.Infrastructure.RepositoryManager.Query;
public partial class Query : IQuery
{
    private readonly DatabaseContext _context;
    ICountryQuery _Country { get;set; }
    IHotelQuery _Hotel { get;set; }
    public Query(DatabaseContext context) {
        _context = context;
    }
    public ICountryQuery Country => _Country ??= new CountryQuery(_context);
    public IHotelQuery Hotel => _Hotel ??= new HotelQuery(_context);
     
     public void Dispose() {
        _context.Dispose();
        GC.SuppressFinalize(this);
    }
    public async Task Save() {
        await _context.SaveChangesAsync();
    }
}
