//This file is autogenerated by toolkit
using Hotel_listing.Domain.Entitites;
using Hotel_listing.Infrastructure.DatabaseManager.Configurations.Entities;
using Microsoft.EntityFrameworkCore;

namespace Hotel_listing.Infrastructure.DatabaseManager.Context;
public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions options):base(options)
    { }
    
    public DbSet<Country>? Country { get; set; }
    public DbSet<Hotel>? Hotel { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfiguration(new CountryConfiguration());
        modelBuilder.ApplyConfiguration(new HotelConfiguration());
    }
}
