using System.Dynamic;
using AutoMapper;
using Hotel_listing.Application.Common.Response;
using Hotel_listing.Application.Contracts.DataShaper;
using Hotel_listing.Application.Contracts.RepositoryManager.Command;
using Hotel_listing.Application.Contracts.RepositoryManager.DataAccessor;
using Hotel_listing.Application.Contracts.RepositoryManager.Query;
using Hotel_listing.Domain.Entitites;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_listing.API.Controllers;

[Route("api/[controller]")]
[ApiController]
public partial class BaseController<T>:ControllerBase where T:class
{
    protected readonly ICommands Command;
    protected readonly IQuery Query;
    protected readonly IDataAccessor Db;
    protected readonly IMapper Mapper;
    protected readonly IHttpContextAccessor Context;
    protected readonly IDataShaper<T> DataShaper;

    public BaseController(
        IQuery query,
        ICommands command,
        IDataAccessor db,
        IMapper mapper,
        IHttpContextAccessor context,
        IDataShaper<T> dataShaper)
    {
        Query = query;
        Command = command;
        Db = db;
        Mapper = mapper;
        Context = context;
        DataShaper = dataShaper;
    }

    // A set of virtual methods here which can be override on the children classes 
    #region HandleResponse overloaded methods
    protected virtual ActionResult ResponseBuilder(dynamic response)
    {
        switch (response.StatusCode)
        {
            case StatusCodes.Status200OK:
                return Ok(response); 
            case StatusCodes.Status201Created:
                return Created("",response); 
            case StatusCodes.Status204NoContent:
                return NoContent(); 
            case StatusCodes.Status400BadRequest:
                return BadRequest(response);
            case StatusCodes.Status401Unauthorized:
                return Unauthorized(response);
            case StatusCodes.Status403Forbidden:
                return Forbid(response);
            case StatusCodes.Status404NotFound:
                return NotFound(response);
            case StatusCodes.Status409Conflict:
                return Conflict(response);
            default:
                return Ok(response);
        }
    }
    
    protected virtual ActionResult HandleResponse(BaseResponse<List<T>,BaseError> response)
    {
        return ResponseBuilder(response);
    }
    protected virtual ActionResult HandleResponse(BaseResponse<T,BaseError> response)
    {
        return ResponseBuilder(response);
    }
    #region Autogenerated Country
    protected virtual ActionResult HandleResponse(CountryResponse<List<Country>> response)
    {
        return ResponseBuilder(response);
    }
    protected virtual ActionResult HandleResponse(CountryResponse<Country> response)
    {
        return ResponseBuilder(response);
    }
    protected virtual ActionResult HandleResponse(CountryResponse<List<ExpandoObject>> response)
    {
        return ResponseBuilder(response);
    }
    protected virtual ActionResult HandleResponse(CountryResponse<ExpandoObject> response)
    {
        return ResponseBuilder(response);
    }
    #endregion
    #endregion
}